"""create: users table

Revision ID: d78161ea1b37
Revises: 
Create Date: 2021-07-25 16:22:10.786498

"""
from datetime import datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

from src.contexts.standard.aggregates.auth.domain import model

# revision identifiers, used by Alembic.
revision = "d78161ea1b37"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table(
        "users",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            default=lambda: str(uuid4()),
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            nullable=False,
            default=lambda: datetime.today(),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            nullable=False,
            default=lambda: datetime.today(),
            onupdate=lambda: datetime.today(),
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False, default=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )

    op.bulk_insert(
        users,
        [
            {
                "email": "boilerplate@mail.com",
                "password": model.User.hashpass("123"),
                "username": "boilerplate",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
